/* #define RT_OTVET_CACHE_ET */
/* #define RT_OTVET_CACHE_RF */

#define RT_TRANSFER
#define RT_TRANSFER_METHOD RT_METHOD_OTVET
#define RT_OUTPUT

#define RT_OTVET_SAVE_FLUX 
#define RT_CHEMISTRY
#define RT_COMPUTE_LW_RATE 
#define RT_UV 
#define RT_LWBANDS 
/* #define RT_PARALLEL_NUM_OPENMP_BUFFERS 8 */

