#define RT_OUTPUT

#define RT_TRANSFER
#define RT_TRANSFER_METHOD 	RT_METHOD_OTVET
#define RT_EXTERNAL_BACKGROUND 	RT_BACKGROUND_SELFCONSISTENT
#define RT_ADD_EXTERNAL_QSO_BACKGROUND

#define RT_LYMAN_ALPHA_HEATING
/*
#define RT_CHEMISTRY
#define RT_UV 
#define RT_LWBANDS 
*/

#define RT_OTVET_CACHE_RF
#define RT_OTVET_CACHE_ET

#define RT_PARALLEL_NUM_OPENMP_BUFFERS 8
#define RT_PARALLEL_USE_MPI


