
all:
	@echo ""
	@echo "  It is not recommended to compile ART winin the SVN tree."
	@echo "  Please use Makefile.template and follow the instructions"
	@echo "  on the top of that file."
	@echo ""


